#!/usr/bin/python3
# Copyright (C) 2022 Free Software Foundation, Inc.
# This file is part of the GNU C Library.
#
# The GNU C Library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# The GNU C Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with the GNU C Library; if not, see
# <https://www.gnu.org/licenses/>.
"""Generate macros for getting GPR name of a certain size

Inputs: None
Output: Prints header fill to stdout

API:
    VGPR(reg_name)
        - Get register name VEC_SIZE component of `reg_name`
    VGPR_SZ(reg_name, reg_size)
        - Get register name `reg_size` component of `reg_name`
"""

import sys
from datetime import datetime

registers = [["rax", "eax", "ax", "al"], ["rbx", "ebx", "bx", "bl"],
             ["rcx", "ecx", "cx", "cl"], ["rdx", "edx", "dx", "dl"],
             ["rbp", "ebp", "bp", "bpl"], ["rsp", "esp", "sp", "spl"],
             ["rsi", "esi", "si", "sil"], ["rdi", "edi", "di", "dil"],
             ["r8", "r8d", "r8w", "r8b"], ["r9", "r9d", "r9w", "r9b"],
             ["r10", "r10d", "r10w", "r10b"], ["r11", "r11d", "r11w", "r11b"],
             ["r12", "r12d", "r12w", "r12b"], ["r13", "r13d", "r13w", "r13b"],
             ["r14", "r14d", "r14w", "r14b"], ["r15", "r15d", "r15w", "r15b"]]

mask_insns = ["kmov", "kortest", "kor", "ktest", "kand", "kxor"]
mask_insns_ext = ["b", "w", "d", "q"]

cr = """
   Copyright (C) {} Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.  */
"""

print("/* This file was generated by: {}.".format(sys.argv[0]))
print(cr.format(datetime.today().year))

print("#ifndef _REG_MAP_MACROS_H")
print("#define _REG_MAP_MACROS_H\t1\n")
for reg in registers:
    for i in range(0, 4):
        for j in range(0, 4):
            print("#define {}_{}\t{}".format(reg[j], 8 << i, reg[3 - i]))

print("")
for reg in registers:
    print("#define V{}\tVGPR({})".format(reg[0].upper(), reg[0]))

print("")
for mask_insn in mask_insns:
    for i in range(0, 4):
        print("#define {}_{}\t{}{}".format(mask_insn, 8 << i, mask_insn,
                                           mask_insns_ext[i]))

print("")
for mask_insn in mask_insns:
    print("#define {}V \tVKINSN_SZ({}, REG_WIDTH)".format(mask_insn, mask_insn))
print("")

print("#ifndef REG_WIDTH")
print("#define REG_WIDTH VEC_SIZE")
print("#endif")
print("#define PRIM_VGPR_SZ(reg_name, reg_size)\treg_name##_##reg_size")
print("#define VGPR_SZ(reg_name, reg_size)\tPRIM_VGPR_SZ(reg_name, reg_size)")
print("#define VGPR(reg_name)\tVGPR_SZ(reg_name, REG_WIDTH)")
print("#define VKINSN_SZ(insn, reg_size)\tPRIM_VGPR_SZ(insn, reg_size)")

print("\n#endif")
